// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5pWvdLmr14bS0jKKpLcDRaL6GCAPe_4E',
    appId: '1:898742549007:web:214d5985ca9827685f817a',
    messagingSenderId: '898742549007',
    projectId: 'lumimemohack',
    authDomain: 'lumimemohack.firebaseapp.com',
    storageBucket: 'lumimemohack.firebasestorage.app',
    measurementId: 'G-LVVSPFH0Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAPseKj_38_mueAZAlGkn5oUau6zTIcs',
    appId: '1:898742549007:android:d75a4430b4f81bc75f817a',
    messagingSenderId: '898742549007',
    projectId: 'lumimemohack',
    storageBucket: 'lumimemohack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNyZxkooa2Jk1PHN3c_IAXNv4Xmt-fTY',
    appId: '1:898742549007:ios:cb3657265931f8b65f817a',
    messagingSenderId: '898742549007',
    projectId: 'lumimemohack',
    storageBucket: 'lumimemohack.firebasestorage.app',
    iosBundleId: 'com.example.lumimemohackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPNyZxkooa2Jk1PHN3c_IAXNv4Xmt-fTY',
    appId: '1:898742549007:ios:cb3657265931f8b65f817a',
    messagingSenderId: '898742549007',
    projectId: 'lumimemohack',
    storageBucket: 'lumimemohack.firebasestorage.app',
    iosBundleId: 'com.example.lumimemohackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5pWvdLmr14bS0jKKpLcDRaL6GCAPe_4E',
    appId: '1:898742549007:web:5d9d365fe3565ddf5f817a',
    messagingSenderId: '898742549007',
    projectId: 'lumimemohack',
    authDomain: 'lumimemohack.firebaseapp.com',
    storageBucket: 'lumimemohack.firebasestorage.app',
    measurementId: 'G-P8LN8HYX3C',
  );

}