// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwgwmKoP4Mk5J2kb90YzOwaR5ZBvnUROQ',
    appId: '1:995882911909:web:c1a34de1f10def45ffa54c',
    messagingSenderId: '995882911909',
    projectId: 'lumimemo-ai',
    authDomain: 'lumimemo-ai.firebaseapp.com',
    storageBucket: 'lumimemo-ai.firebasestorage.app',
    measurementId: 'G-93256L4MMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzj0mmWDUhCXFPZpYyCaFFu4XBa88NgbY',
    appId: '1:995882911909:android:381f927d3c062dd9ffa54c',
    messagingSenderId: '995882911909',
    projectId: 'lumimemo-ai',
    storageBucket: 'lumimemo-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkOy0ArdBhRgRbniQwqZ7o6Ba3wkC0JHU',
    appId: '1:995882911909:ios:ceb0312ef88114f4ffa54c',
    messagingSenderId: '995882911909',
    projectId: 'lumimemo-ai',
    storageBucket: 'lumimemo-ai.firebasestorage.app',
    iosBundleId: 'com.example.lumimemohackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkOy0ArdBhRgRbniQwqZ7o6Ba3wkC0JHU',
    appId: '1:995882911909:ios:ceb0312ef88114f4ffa54c',
    messagingSenderId: '995882911909',
    projectId: 'lumimemo-ai',
    storageBucket: 'lumimemo-ai.firebasestorage.app',
    iosBundleId: 'com.example.lumimemohackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwgwmKoP4Mk5J2kb90YzOwaR5ZBvnUROQ',
    appId: '1:995882911909:web:ce388f6395839c8affa54c',
    messagingSenderId: '995882911909',
    projectId: 'lumimemo-ai',
    authDomain: 'lumimemo-ai.firebaseapp.com',
    storageBucket: 'lumimemo-ai.firebasestorage.app',
    measurementId: 'G-WCNYKJNR8S',
  );

}